//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_New_Timetable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Initial_DatabaseEntities3 : DbContext
    {
        public Initial_DatabaseEntities3()
            : base("name=Initial_DatabaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<subject_lecturer_room> subject_lecturer_room { get; set; }
    }
}
