//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_New_Timetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_lecturer_room
    {
        public int subject_subject_id { get; set; }
        public int lecturer_lecturer_id { get; set; }
        public int room_room_id { get; set; }
    
        public virtual lecturer lecturer { get; set; }
        public virtual room room { get; set; }
        public virtual subject subject { get; set; }
    }
}
